# Generated by Django 5.2.1 on 2025-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_permissions': (), 'verbose_name': 'کاربر سفارشی', 'verbose_name_plural': 'کاربران سفارشی'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='گروه\u200cهایی که این کاربر به آن\u200cها تعلق دارد.', related_name='customuser_set_groups', related_query_name='user', to='auth.group', verbose_name='گروه\u200cها'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default-avatar.png', upload_to='profile_images/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='دسترسی\u200cهای خاص برای این کاربر.', related_name='customuser_set_permissions', related_query_name='user', to='auth.permission', verbose_name='دسترسی\u200cهای کاربر'),
        ),
    ]
