# Generated by Django 5.2.1 on 2025-06-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_form',
            new_name='valid_from',
        ),
    ]
